### ISSUE TITLE
Database question keys

### ISSUE THREAD

**Issue by telferha** [pbremer/astronomy-app#1]
multiplechoice Option, multiplechoice question and answer tables have connecting forigen keys issues. in addition this may affect the numerical question table and the questions table

**Comment by pbremer** [comment]
limitation with JPA, closing

**Comment by pbremer** [comment]
actually there is a way to make it make more sense. reopening

**Comment by pbremer** [comment]
fixed in commit aaff37f1ff61c4dd8510535e445be52adceb19fb, closing
