### ISSUE TITLE
Deleting self from group should redirect to module page

### ISSUE THREAD

**Issue by pbremer** [pbremer/astronomy-app#28]
When deleting self from group member, server returns json list of remaining group members. Instead, server should send redirect command to the list of modules page

**Comment by pbremer** [comment]
deferring fix for spring 3

**Comment by Nazariy995** [comment]
@pbremer I would suggest, just return a 400 or something and let me take care of it on the front end. That way people will have a better feedback as to why they got an error.

**Comment by pbremer** [comment]
@Nazariy995 a 400 error is reserved for when the user does some generic illegal action. Deleting self is not illegal. Instead I can send a redirect instruction. If that redirect does not work for whatever reason, then keep on the lookout for a 301 status

**Comment by Nazariy995** [comment]
@pbremer Yeah! I mean the status code can be whoever code best suits this information. It's just that with the status code I can do the right appropriate thing. But we will take care of it in Sprint 3 like you said.
