### ISSUE TITLE
Checkin Exception 

### ISSUE THREAD

**Issue by Nazariy995** [pbremer/astronomy-app#32]
Request URL:http://localhost:8080/rest/student/course/course1A/module/mod3-course1A/group/04e84d69-0fce-418e-92c0-5979e77345b5/checkin?courseUserId=stud1-course1A
Request Method:POST
Status Code:500 
Remote Address:[::1]:8080
{  
   "timestamp":1486957846743,
   "status":500,
   "error":"Internal Server Error",
   "exception":"javax.persistence.PersistenceException",
   "message":"org.hibernate.exception.SQLGrammarException: could not extract ResultSet",
   "path":"/rest/student/course/course1A/module/mod3-course1A/group/04e84d69-0fce-418e-92c0-5979e77345b5/checkin"
}

**Comment by Nazariy995** [comment]
Payload: 
{  
   "password":"asdlfkjasdlf",
   "username":"user1@umich.edu"
}

**Comment by Nazariy995** [comment]
Never mind, it's all good!

**Comment by pbremer** [comment]
body should be:
`
 {
    "email": "{SOME_EMAIL}",
    "password": "{THE_PASSWORD}"
}
`
