### ISSUE TITLE
Save Answers Error 

### ISSUE THREAD

**Issue by Nazariy995** [pbremer/astronomy-app#42]
Request:
![screen shot 2017-03-02 at 7 02 08 pm](https://cloud.githubusercontent.com/assets/6589966/23532699/cf22943a-ff7a-11e6-9a9f-8ff011e2e602.png)
Response:
{  
    "timestamp":1488499308783,
    "status":400,
    "error":"Bad Request",
    "exception":"org.springframework.http.converter.HttpMessageNotReadableException",
    "message":"Could not read document: Can not deserialize instance of java.lang.String out of START_OBJECT token\n at [Source: java.io.PushbackInputStream@6240655a; line: 1, column: 30] (through reference chain: java.util.LinkedHashMap[\"item1-page1-mod1-course1A\"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token\n at [Source: java.io.PushbackInputStream@6240655a; line: 1, column: 30] (through reference chain: java.util.LinkedHashMap[\"item1-page1-mod1-course1A\"])",
    "path":"/rest/student/course/course1A/module/mod1-course1A/group/group1-course1A%20/answers/save"
}

**Comment by Nazariy995** [comment]
@pbremer I am not sure what's going on. Maybe I need to format it differently?

**Comment by pbremer** [comment]
@Nazariy995 nope, thats my bad. im on it

**Comment by Nazariy995** [comment]
@pbremer All working good! 👍
