### ISSUE TITLE
URLs not working correctly due to HTML 5 mode! 

### ISSUE THREAD

**Issue by Nazariy995** [pbremer/astronomy-app#5]
# Problem
With HTML5 Mode when going to a page like http://localhost:8080/home/student works within the application because it's basically one html page.
However, when I try to refresh, it says 404 not found. I did some research and realized it's because the server is searching for home/student.html which is not there obviously since everything is served from index.html, and angular just routes that one page internally.
# Solution
- Solution could be to not use html5 mode, which will make the page look like this http://localhost:8080/#/home/student
- Or have a catch all on the server that right away redirects to index.htm

**Comment by pbremer** [comment]
another solution is to make all frontend urls contain a . (period)

for example; /home/student**.htm**

marking as deferred and low priority
